### PR TITLE
add elixir mix support

### PR DESCRIPTION
**Pull request by emmanueltouzery**
first off, thank you very much for this plugin, it really great! much appreciated!

i've written some integration for the elixir mix system. the contents of the elixir files is elixir code, so it's not possible to parse it from lua, the only way to list the tasks is to run `mix help`. The downside is that that takes a little bit of time to run the help, so that slows down the display a little, but there's no other way that i can think of.

### CODE REVIEW

**Review by stevearc — CHANGES_REQUESTED** [review]
Thanks for submitting a PR! It's great to get support for more frameworks! The approach of running `mix help` and parsing the output is fine, but I do have a couple of requests:

First: remove the dependency on plenary. Overseer has no hard dependencies and I'd like to keep it that way unless a significant need arises.

I'd recommend taking a look at the [make template](https://github.com/stevearc/overseer.nvim/blob/master/lua/overseer/template/make.lua). It uses a treesitter parser (if installed) to get the targets, and falls back to parsing make output. You don't have to do the treesitter parser part of that if you don't want, but you can template the process output parsing off of this file. Note that in this case the generator accepts a callback function `cb` and calls it with the results once parsing has completed, and also that it returns `nil` from the generator function itself.

I do think that the sync/async API is a bit rough at the moment and could use some polishing. I'll also probably add a feature in the nearish future to cache the generator results so you only get that pause once.

**Comment by emmanueltouzery** [comment]
thank you for the fast feedback! I've removed the plenary dependency now. Regarding the treesitter support... I'm not sure what it would bring, and that would probably represent quite some learning for me, since I have no idea about it.

**Comment by stevearc** [comment]
Yeah, the treesitter thing is totally optional. You can ignore that part of the make template and look just at how it parses the command output

**Comment by emmanueltouzery** [comment]
if it wasn't clear, i did that, force pushed and the PR now uses the vim api like the make template.

**Comment by stevearc** [comment]
Awesome, thanks for the contribution!

**Pull request merged**
