### PR TITLE
npm: smarter package.json file detection

### LINKED ISSUE #242: feature request: wrong package.json picked up in certain project configurations
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I've just tried upgrading from a very old version of overseer that was taking the current folder into account to operate, instead of the new setup which is to take into account the current file's folder.

It causes an issue with projects having multiple `package.json` files.

### Provide background

Some projects have package.json files in subfolders, which are not the main project package.json file but rather some submodule marker. This seems prevalent in react-native projects. See this for instance:
https://stackoverflow.com/questions/51701191/react-native-has-something-to-use-local-folders-as-package-name-what-is-it-ca

I work on such a project. So overseer picks up that package.json in the subfolder, and not the main package.json at the root of project, which is the one containing the important tasks.

It would be nice if overseer could auto-detect that this package.json is not the real one... Or alternatively (and maybe this is already possible) if there was a not-too-verbose way for the user to give overseer the path to take into account to find the package.json, or something like that.

### What is the significance of this feature?

nice to have

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by emmanueltouzery**
fixes #242
Some projects have package.json files in subfolders, which are not the main project package.json file but rather some submodule marker. This seems prevalent in react-native projects. See this for instance: https://stackoverflow.com/questions/51701191/react-native-has-something-to-use-local-folders-as-package-name-what-is-it-ca To cover that case, we search for package.json files starting from the current file folder, up to the working directory, and pick the outermost candidate.

### CODE REVIEW

**Review by stevearc — CHANGES_REQUESTED** [review]
Unfortunately I think the fix is more complex than this. There is good reason to take the package.json closest to the file; if you're working in a monorepo with multiple subpackages you may want to see tasks related to the subpackage of the current file rather than the highest-level package file. For example:

```
project/            <-- vim cwd
  package.json
  subproject/
    package.json
    src/
      package.json  <-- dummy package file
      index.ts      <-- open file
```
We want to list tasks from _all_ of the package.json files, it's just that the dummy file won't have any.

There's also the case where vim is in a subfolder of the project directory and we have to search _above_ the cwd.

```
project/
  package.json
  src/         <-- vim cwd
    index.ts   <-- open file
```

**Comment by emmanueltouzery** [comment]
Not stopping when searching above is a little risky though, right? Let's say we limit at two package.json files to limit false positives, that won't help for most projects where there is only one package.json file, then if the user has a stray package.json file in their home folder we could grab it.
Ideally we'd detect the root of the repo and stop there, but I guess it's out of scope...

My idea of stopping at the root was if the user uses a rooter plugin to set the current folder to the root of the repo, but I agree that overseer shouldn't rely on that.

**Comment by emmanueltouzery** [comment]
Ok maybe like that .. limit at two, recurse up in an unlimited manner.
If the first package.json file has tasks, take only these.
If it doesn't, take the tasks from the second package.json file.

That solves my issue and seems robust enough to me?

**Comment by stevearc** [comment]
This is why in the original issue I said "It should search starting from the path of the current file terminating at either the first package.json or the current working directory, **whichever comes second**"

I think we should take an unlimited amount of `package.json` files, terminating at the current directory. However, if we don't find any by the time we reach the current directory we should keep searching upwards, terminating at the first `package.json` file.

**Comment by stevearc** [comment]
LGTM thanks!

**Pull request merged**
